from dash.development.base_component import Component
from typing import Any

def Text(*args: Any, **kwargs: Any) -> Component: ...
def Alert(*args: Any, **kwargs: Any) -> Component: ...
def Button(*args: Any, **kwargs: Any) -> Component: ...
def Title(*args: Any, **kwargs: Any) -> Component: ...
def Container(*args: Any, **kwargs: Any) -> Component: ...
def MantineProvider(*args: Any, **kwargs: Any) -> Component: ...
# 필요한 컴포넌트 계속 추가